# Generated by Django 5.2.8 on 2025-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_agendamento_options_alter_congregacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacao',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='usuarioprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
