# Generated by Django 5.2.8 on 2025-12-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_remove_congregacao_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(help_text='Ex: Reunião, Manutenção, Evento especial', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='agendamento.congregacao')),
            ],
        ),
    ]
