# Generated by Django 5.2.8 on 2025-12-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_bloqueioagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioprofile',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
