# Generated by Django 5.2.8 on 2025-12-27 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_usuarioprofile_is_superadmin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='congregacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamento.congregacao'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('congregacao', 'data', 'horario')},
        ),
    ]
